name: bomba_timer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.4.0
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_native_splash: ^2.4.6
  icons_launcher: ^3.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  styled_text: ^8.1.0
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/


#dart run icons_launcher:create --path assets/icons/icons_launcher.yaml
#dart pub run flutter_native_splash:create --path=assets/icons/flutter_native_splash.yaml